# MongoDB ????? JVM? ???? ???
spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/prac?replicaSet=rs0&authSource=admin
      database: prac
logging:
  level:
    root: debug
