version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo:latest
    command: mongos --configdb config_rs/configsvr1:27017,configsvr3:27017,configsvr3:27017 --port 27017 --bind_ip_all
    ports:
      - 27017:27017